addSbtPlugin("com.eed3si9n"  % "sbt-assembly"  % "2.3.1")
addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("net.nmoncho"   % "sbt-dependency-check" % "1.8.5")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.1")
