apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: ''
      tracesToMetrics:
        datasourceUid: ''
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: ''
